### ISSUE TITLE
Can't start communication to my Display

### ISSUE THREAD

**Issue by houselightguy** [raspilc/ioBroker.i2clcd#10]
Hello i have the problem that the adapter don't want connect to host the light booth are red.
When i look in the log there following problem: 

host.raspberrypi | 2021-04-29 15:59:16.087 | info | Restart adapter system.adapter.i2clcd.0 because enabled
-- | -- | -- | --
host.raspberrypi | 2021-04-29 15:59:16.086 | error | instance system.adapter.i2clcd.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.raspberrypi | 2021-04-29 15:59:16.085 | error | Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
host.raspberrypi | 2021-04-29 15:59:16.085 | error | Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
host.raspberrypi | 2021-04-29 15:59:16.084 | error | Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/lcdi2c/index.js:1:18)
host.raspberrypi | 2021-04-29 15:59:16.084 | error | Caught by controller[0]:     at require (internal/modules/cjs/helpers.js:88:18)
host.raspberrypi | 2021-04-29 15:59:16.083 | error | Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:952:19)
host.raspberrypi | 2021-04-29 15:59:16.082 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
host.raspberrypi | 2021-04-29 15:59:16.082 | error | Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:928:32)
host.raspberrypi | 2021-04-29 15:59:16.081 | error | Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
host.raspberrypi | 2021-04-29 15:59:16.080 | error | Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:1027:27)
host.raspberrypi | 2021-04-29 15:59:16.080 | error | Caught by controller[0]:     at wrapSafe (internal/modules/cjs/loader.js:979:16)
host.raspberrypi | 2021-04-29 15:59:16.079 | error | Caught by controller[0]: SyntaxError: Unexpected token '>'
host.raspberrypi | 2021-04-29 15:59:16.079 | error | Caught by controller[0]: 		          ^
host.raspberrypi | 2021-04-29 15:59:16.078 | error | Caught by controller[0]: 		if ( line > 0 && line <= this.rows ) {
host.raspberrypi | 2021-04-29 15:59:16.077 | error | Caught by controller[0]: /opt/iobroker/node_modules/lcdi2c/lcdi2c.js:295
host.raspberrypi | 2021-04-29 15:59:14.202 | info | instance system.adapter.i2clcd.0 started with pid 10514

**Comment by raspilc** [comment]
Hi! I need  some additional informations: Which version of nodejs is running and which version of js-controller? Is i2c enabled in raspi-config? What kind of display do you use?

**Comment by houselightguy** [comment]
Hi! thx for your fast answer. Node.js ist v14.16.1 js-controller is 3.2.16. Yes i2c is enabled in raspi-config. it ist 16x2 at hd44780

**Comment by raspilc** [comment]
Mmhhh,a library is not compatible with nodejs 14. I will try to solve this next days. At the moment it works with nodejs 10 only. But,thank you,good to know ;-)

**Comment by raspilc** [comment]
Hi! Should work now :-)
