### ISSUE TITLE
can not write to my display

### ISSUE THREAD

**Issue by Bastelritius** [raspilc/ioBroker.i2clcd#2]
Hello,

I´m using iobroker and I connected my display to my Raspberry 2 via GPIO and I2C adapter with adress 0x27. With i2cdetect -y 1 I can see the device.
I set up the values to the Adapter in iobroker but I get the warn message: (2706) Cannot write to LCD-Display!
What can be the reason?

Thanks

**Comment by raspilc** [comment]
Hello,
is the display address given as decimal value in the adapter config? Please try 39 for address.

**Comment by Bastelritius** [comment]
Hi, yes now it is working. Many thanks :)
Only one thing. My Display is a 16x4, not a 20x4. Is it possible to adapt it in the code?

**Comment by raspilc** [comment]
Yes of course!I am working for support 16x2 displays at the moment. The update comes soon :-) I added the tip for using decimal value in the address field. Thanks for the hint!

**Comment by Bastelritius** [comment]
You mean you are working on support for 16x4 displays? That would be very nice. Many thanks.

**Comment by raspilc** [comment]
Ok,i had seen your message without my glasses ;-) What happened on your 16x4 display? I haven‘t such a display for testing. The library i use supports 16x2 and 20x4 only.I can try to implement a workaround for this but i‘m not sure if it is possible.

**Comment by Bastelritius** [comment]
First and second row is fine, but 3 and 4 line started not at the beginning. Always some empty space in the line. I think these are the 4 characters from the lines before (16 characters instead of 20).
